"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Error = exports.Item = exports.Totem = exports.Summoner = exports.User = exports.sequelize = void 0;
const sequelize_1 = __importDefault(require("sequelize"));
const config_1 = __importDefault(require("../config/config"));
const user_1 = __importDefault(require("./user"));
exports.User = user_1.default;
const summoner_1 = __importDefault(require("./summoner"));
exports.Summoner = summoner_1.default;
const totem_1 = __importDefault(require("./totem"));
exports.Totem = totem_1.default;
const item_1 = __importDefault(require("./item"));
exports.Item = item_1.default;
const error_1 = __importDefault(require("./error"));
exports.Error = error_1.default;
const env = process.env.NODE_ENV || "development";
const config = config_1.default[env];
exports.sequelize = new sequelize_1.default.Sequelize(config.database, config.username, config.password, config);
user_1.default.initiate(exports.sequelize);
summoner_1.default.initiate(exports.sequelize);
totem_1.default.initiate(exports.sequelize);
item_1.default.initiate(exports.sequelize);
error_1.default.initiate(exports.sequelize);
user_1.default.associate();
summoner_1.default.associate();
totem_1.default.associate();
item_1.default.associate();
error_1.default.associate();
